runmode: debug               # 开发模式, debug, release, test
port: :8080                  # HTTP绑定端口
name: sv_blog_api              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: root